version: '{build}'
image: Visual Studio 2017
build_script:
- ps: ./dotnet-install.ps1 -version 2.0.0
- ps: dotnet --info
- ps: ./build.ps1
test: off
artifacts:
- path: artifacts/packages/*.nupkg
deploy:
  provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key:
    secure: PWCeOQ12fgAhPiBjgkBAqHbvaPQArarsO2sI+8KCeXjBjE+AHaMIMW8b7efmDzQ6
  skip_symbols: true
  artifact: /artifacts\/packages\/.+\.nupkg/
